name: Spellcheck Action

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: rojopolis/spellcheck-github-actions@0.17.0
      name: Spellcheck
      with:
        config_path: config/spellcheck.yml
        task_name: Markdown
